@startuml
rectangle postacie {
  rectangle towarzysze
  rectangle powiernicy as "powiernicy\npierścienia"
  rectangle Gollum
  rectangle slugi as "sługi"
}
rectangle jednostki {
  rectangle regularne
  rectangle elitarne
}
rectangle dowodzcy as "dowódzcy" {
  rectangle Nazgule as "Nazgûle"
  rectangle dowodzcyWolnychLudow as "dowódzcy\nWolnych\nLudów"
}
rectangle druzyna as "Drużyna\nPierścienia"
rectangle armia
rectangle narod as "naród" {
  rectangle region
  note bottom of region: **wolny** dla gracza\ngdy brak wrogich\narmii i osad\n(poza obleganą\ntwierdzą)
}

towarzysze ...> region: po <font color="BlueViolet">opuszczeniu\nDrużyny Pierścienia;\nmoże poruszać się\nsamodzielnie lub z armią
towarzysze ..> druzyna: są częścią\ndrużyny dopóki\njej nie <font color="BlueViolet">opuszczą;\njeden przewodzi
Gollum ..> druzyna: podąża za drużyna;\nprzewodzi, gdy\n<font color="BlueViolet">braknie towarzyszy
powiernicy --> druzyna
slugi ---> region

Nazgule ---> region: może poruszać się\nsamodzielnie lub z armią;\nbez przyjaznej armii\nnie wchodzi do\nwrogiej twierdzy
dowodzcyWolnychLudow ---> region: bez\nprzyjaznej\narmii\nginie
jednostki --> armia: "max 10 /\nmax 5 (w oblężonej twierdzy)"

armia --> region
druzyna --> region

rectangle osada {
  rectangle wioska
  rectangle miasto
  rectangle twierdza
}
rectangle fortyfikacja

region <--- osada
region <--- fortyfikacja

@enduml
