@startuml
rectangle postacie {
  rectangle towarzysze
  rectangle powiernicy as "powiernicy\npierścienia"
  rectangle Gollum
  rectangle slugi as "sługi" {
    rectangle Saruman
    rectangle rzecznikSaurona as "Rzecznik Saurona"
    rectangle czarnoksieznik as "Czarnoksiężnik\nz Angmaru"
  }
}
rectangle jednostki {
  rectangle regularne
  rectangle elitarne
}
rectangle dowodzcy as "dowódzcy" {
  rectangle Nazgule as "Nazgûle"
  rectangle dowodzcyWolnychLudow as "dowódzcy\nWolnych\nLudów"
}
rectangle druzyna as "Drużyna\nPierścienia"
rectangle armia
rectangle narod as "naród" {
  rectangle region
  note bottom of region: **wolny** dla gracza\ngdy brak wrogich\narmii i osad\n(poza obleganą\ntwierdzą)
}

czarnoksieznik -> Nazgule

towarzysze ...> region: po <font color="BlueViolet">opuszczeniu\nDrużyny Pierścienia;\n* może poruszać się\nsamodzielnie lub z armią\n* <font color="DarkOrange">musi się zatrzymać w\n<font color="DarkOrange">regionie z twierdzą Cienia\n* <font color="IndianRed">nie może przybyć/opuścić\n<font color="IndianRed">regionu z przyjazną\n<font color="IndianRed">oblężoną twierdzą
towarzysze ..> druzyna: są częścią\ndrużyny dopóki\njej nie <font color="BlueViolet">opuszczą;\njeden przewodzi
Gollum ..> druzyna: podąża za drużyna;\nprzewodzi, gdy\n<font color="BlueViolet">braknie towarzyszy
powiernicy --> druzyna
rzecznikSaurona ---> region: \n* może poruszać się\nsamodzielnie lub z armią\n* <font color="Red">bez armii nie może przybyć\n<font color="Red">do regionu z wrogą\n<font color="Red">nieoblężoną twierdzą\n* <font color="IndianRed">nie może przybyć/opuścić\n<font color="IndianRed">regionu z przyjazną\n<font color="IndianRed">oblężoną twierdzą
Saruman ---> region: nie może\nopuścić\nOrthanku

Nazgule ---> region: \n* może poruszać się\nsamodzielnie lub z armią\n* <font color="Red">bez armii nie może przybyć\n<font color="Red">do regionu z wrogą\n<font color="Red">nieoblężoną twierdzą
dowodzcyWolnychLudow ---> region: bez\nprzyjaznej\narmii\nginie
jednostki --> armia: "max 10 /\nmax 5 (w oblężonej twierdzy)"

armia --> region
druzyna --> region

rectangle osada {
  rectangle wioska
  rectangle miasto
  rectangle twierdza
}
rectangle fortyfikacja

region <--- osada
region <--- fortyfikacja

@enduml
